[package]
name = "tcpchat-server"
version = "0.1.0"
edition = "2024"

[dependencies]
local-ip-address = "0.6.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
